name: Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm install

      - name: Generating a parser
        run: |
            node_modules/.bin/tree-sitter init-config
            node_modules/.bin/tree-sitter generate

      - name: Run NIST COBOL85 tests
        run: make nist

      - name: Upload results of NIST COBOL85 tests
        uses: actions/upload-artifact@v3
        with:
          name: NIST_COBOL85_test
          path: test/cobol85

      - name: Run tests
        run: node_modules/.bin/tree-sitter test
